.github/workflows/build.yaml, README.md
* addressing issue https://github.com/osrf/rmf_demos/issues/19
* made the necessary changes to build test as well
=> made changes according to issues

rmf_demo_maps/maps/office/office.building.yaml
Following [latest traffic-editor update](https://github.com/osrf/traffic_editor/pull/94). This should resolve #34
=> Set coke model to non-static

rmf_gazebo_plugins/src/teleport.cpp
apologies for the steaming un-formatted mess before, this PR should reflect only the necessary changes, following https://github.com/osrf/rmf_demos/pull/41.
=> implement visual reset of coke can in 2s via fixed initial pose

rmf_demo_maps/CMakeLists.txt
Works with this, https://github.com/osrf/traffic_editor/pull/132, to build our demo from `traffic_editor` maps
=> Started using new commands from building_map_tools

rmf_demo_maps/CMakeLists.txt
* calling `message` in `add_custom_command` creates interesting issues
=> Move message call outside of custom command call

.github/workflows/build.yaml, .github/workflows/style.yml
Signed-off-by: Yadunund Vijay <yadunund@openrobotics.org>
=> Actions run on pull requests

rmf_rviz_plugin/CMakeLists.txt
=> change deprecated ament_export_interfaces to ament_export_targets (foxy)

demos/launch/include/airport_terminal/airport_terminal.rviz, demos/launch/include/clinic/clinic.rviz, demos/launch/include/office/office.rviz
Add floorplan to rviz in Demo Worlds. This should merge first: https://github.com/osrf/rmf_schedule_visualizer/pull/78
=> add floorplan to rviz

demos/CHANGELOG.rst, rmf_dashboard_resources/CHANGELOG.rst, rmf_demo_assets/CHANGELOG.rst, rmf_demo_maps/CHANGELOG.rst, rmf_demo_tasks/CHANGELOG.rst, rmf_gazebo_plugins/CHANGELOG.rst, rmf_rviz_plugin/CHANGELOG.rst
Signed-off-by: Yadunund Vijay <yadunund@openrobotics.org>
=> Updated changelogs for release 1.1

rmf_demo_maps/maps/clinic/clinic.building.yaml
Signed-off-by: Aaron Chong <aaronchongth@gmail.com>
* works with https://github.com/osrf/traffic_editor_assets/pull/15
=> Using newly rotated CGMClassic model and thumbnail

docs/installation.md
Update a few sections of the installation doc after following along on a clean Ubuntu 20.04 machine.
Signed-off-by: Morgan Quigley <morgan@osrfoundation.org>
=> update installation doc with notes from a clean ubuntu 20.04 machine

rmf_dashboard_resources/package.xml, rmf_demo_tasks/CHANGELOG.rst, rmf_demo_tasks/package.xml
All packages need to have the same version to be released as 1.1.0.
=> Setting all packages to version to 1.1.0

docs/installation.md
hi, just correcting a small mistake in spelling for the line of installing ignition libraries
=> correct misspelling in installation.md

rmf_demo_plugins/rmf_ignition_plugins/src/TeleportDispenser.cpp
Optimization to avoid `AxisAlignedBox` computation when the slotcar moves. With this change, the ingestor ignition plugin makes a service request to the slotcar to read its dimensions instead. Also requires osrf/traffic_editor#271 to be merged.
=> Use service request to get slotcar height instead of reading from its AABB component

rmf_demo_plugins/rmf_plugins_common/CMakeLists.txt
Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>
=> Fixing cmake issue with library install location

rmf_rviz_plugin/CMakeLists.txt
Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>
=> removing specific rules for eloquent

demos/CHANGELOG.rst, demos/package.xml, rmf_dashboard_resources/package.xml, rmf_demo_assets/CHANGELOG.rst, rmf_demo_assets/package.xml, rmf_demo_maps/package.xml, rmf_demo_plugins/rmf_gazebo_plugins/package.xml, rmf_demo_plugins/rmf_ignition_plugins/CHANGELOG.rst, rmf_demo_plugins/rmf_ignition_plugins/package.xml, rmf_demo_plugins/rmf_plugins_common/package.xml, rmf_demo_tasks/package.xml, rmf_rviz_plugin/package.xml
Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>
=> changelogs update and version bump

docs/installation.md, rmf_dashboard_resources/office/dashboard_config.json, rmf_demo_panel/README.md, rmf_demo_panel/rmf_demo_panel/api_server.py
- Update doc on `npm --prefix` path. 
- Added more places on `office.world`. 
- minor cleanup in `api_server`
=> update docs and cleanups

README.md, docs/faq.md
Signed-off-by: Morgan Quigley <morgan@osrfoundation.org>
=> add link to roadmap and fix rmf_core faq link

docs/installation.md, rmf_demo_panel/README.md, rmf_demo_panel/package.xml
Adding flask as system dependencies, there's still some issues that have been recorded at #202 and should be addressed in the near future.
Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>
=> adding npm and flask dependencies, updating install

demos/launch/include/office/office_conflict.launch.xml, rmf_dashboard_resources/office/dashboard_config.json, rmf_demo_maps/maps/office/office.building.yaml, rmf_demo_tasks/rmf_demo_tasks/office_tasks.json
* Connected bottom nodes in the graph
* Removed `cubicle_1` and `cubicle_2`
* Replaced `station_1` with `tinyRobot1_charger`. Moved `tinyRobot2_charger` to below `lounge`
* Updated dashboard config files
=> Modifications to office world navgraph

rmf_demo_panel/rmf_demo_panel/static/src/__tests__/scheduled-task-form.test.tsx, rmf_demo_panel/rmf_demo_panel/static/src/components/forms/scheduled-task-form.tsx, rmf_demo_panel/rmf_demo_panel/static/src/components/styles.tsx
**Changes:**
- Fixed a bug where uploading the same file after submission does not render the text content
- Altered appearance upload button
=> fix: uploading the same json will render the correct text

.gitmodules, Dockerfile, demos/launch/common.launch.xml, docker-compose.yml, docker/rmf_entrypoint.bash
The main controversy about this is the use of submodules, it has some advantages which makes them worthwhile.
1. docker supports submodules, this allows docker images to be built directly from git with `docker build https://github.com/osrf/rmf_demos.git`
2. allows reproducible builds
We do need to make sure the submodules are updated regularly, we can use automated workflows to do that.
How often is rmf-rolling updated? We may not need this if its updated very fast.
=> add dockerfile
